print(True+False)
print(True+True)
print(True-False)
print(True*False)
# print(True/False)
#print(True//False)
print(True//True)
#print(True%False)
print(True%True)
print(True**False)
print(type(True+False))
print(type(True-False))
print(type(True*False))
# print(type(True/False))
# print(type(True//False))
print(type(True/True))
print(type(True//True))
# print(type(True%False))
print(type(True%True))
print(type(True**False))